### ISSUE TITLE
Any suggestions to reduce generated code?

### ISSUE THREAD

**Issue by nikolaydubina** [hedhyw/otelinji#10]
This is nice!

I had similar idea. However, gencoded blocks still looks annoying.

Anything you found or can suggest to reduce this?

(eg, gencode right before compilation and not comitting this; eBPF based tools; somehow hiding it in VSCode/Goland; ????)

Thanks for doing this!

**Comment by hedhyw** [comment]
The most simple solution is to use docker for building binaries (actually I think it is already used) and run this tool just before compiling. We can think more if it is not a suitable solution for some reason.

_There is an inconvenience that trace blocks will not be included locally on `go run` and `go build`, but I don't think it is a big deal._

Thanks!
