### ISSUE TITLE
feat: create an error tracking helper that doesn't set status

### ISSUE THREAD

**Issue by hedhyw** [hedhyw/otelinji#12]
In #11 a status was added to the function `EndSpanWithErr`.

So in order to have the ability to track an error without status, we can create a helper `EndSpanWithWarn` similar to `EndSpanWithErr`, but without calling `span.SetStatus`.

Create a template similar to [the default](https://github.com/hedhyw/otelinji/blob/main/internal/pkg/assets/otel.tmpl) that uses only this helper. Define this template in [this](https://github.com/hedhyw/otelinji/blob/fc2432ecd07c78d8c070afb2b8aa3256fafe60ab/internal/app/app.go#L197) file. So it would be possible to override this behavior in CLI and developers can also manually change the function to desired.

Document changes in [Readme.md](https://github.com/hedhyw/otelinji/blob/fc2432ecd07c78d8c070afb2b8aa3256fafe60ab/README.md).

**Comment by nikolaydubina** [comment]
+ to add to this, might make sense to check what other languages (Java, Ruby, Python - that have automatic instrumentation as well) are doing. Of course, Go deals with errors differently (more often communication through errors happen, elsewhere errors more like `panic`), but can get inspiration/reference.

👍🏻
